<div class="admin_form_row">
	<label for="gallery_image">Галерея изображений</label>
	<div id="fileUpload<?=$key;?>" class="file_upload clearfix">
		<input id="gallery_image<?=$key;?>" type="file" name="gallery_image[<?=$key;?>]" multiple data-table="fields" data-file-type="images" class="file_upload_input" onchange="getUploadFiles('gallery_image<?=$key;?>');" value="">
		<div class="file_viewed clearfix"></div>
		<div id="fileUploaded" class="btn btn_admin" onclick="fileUploadBtn('gallery_image<?=$key;?>');">Добавить файл</div>
		<input class="file_upload_filed" type="hidden" name="gallery_image[<?=$key;?>]" value="">
	</div>
	Порядок отоброжения: <select class="order_fields" name="order[<?=$key;?>]"><option value="-20">-20</option><option value="-19">-19</option><option value="-18">-18</option><option value="-17">-17</option><option value="-16">-16</option><option value="-15">-15</option><option value="-14">-14</option><option value="-13">-13</option><option value="-12">-12</option><option value="-11">-11</option><option value="-10">-10</option><option value="-9">-9</option><option value="-8">-8</option><option value="-7">-7</option><option value="-6">-6</option><option value="-5">-5</option><option value="-4">-4</option><option value="-3">-3</option><option value="-2">-2</option><option value="-1">-1</option><option value="0">0</option><option value="1">1</option><option value="2">2</option><option value="3">3</option><option value="4">4</option><option value="5">5</option><option value="6">6</option><option value="7">7</option><option value="8">8</option><option value="9">9</option><option value="10">10</option><option value="11">11</option><option value="12">12</option><option value="13">13</option><option value="14">14</option><option value="15">15</option><option value="16">16</option><option value="17">17</option><option value="18">18</option><option value="19">19</option><option value="20" selected>20</option></select>
	<p class="admin_form_caption">Можно прикрепить много фотографий. Минимальный размер ширины 820px. Разрешены форматы: JPG, PNG, GIF</p>
</div>